"""initial

Revision ID: 7d7315dd0c6b
Revises: 
Create Date: 2026-04-02 18:34:19.771390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d7315dd0c6b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comparison_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('observation_date', sa.Date(), nullable=False),
    sa.Column('spread_10y2y', sa.Float(), nullable=True),
    sa.Column('spread_10y3m', sa.Float(), nullable=True),
    sa.Column('spread_10y2y_1m_delta', sa.Float(), nullable=True),
    sa.Column('hy_spread', sa.Float(), nullable=True),
    sa.Column('hy_spread_zscore_1y', sa.Float(), nullable=True),
    sa.Column('cpi_yoy', sa.Float(), nullable=True),
    sa.Column('fedfunds', sa.Float(), nullable=True),
    sa.Column('fedfunds_3m_delta', sa.Float(), nullable=True),
    sa.Column('feature_vector', sa.JSON(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comparison_snapshots_observation_date'), 'comparison_snapshots', ['observation_date'], unique=True)
    op.create_table('derived_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('metric_id', sa.String(length=64), nullable=False),
    sa.Column('observation_date', sa.Date(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('source_series', sa.String(length=256), nullable=False),
    sa.Column('window_days', sa.Integer(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('metric_id', 'observation_date', name='uq_derived_metric')
    )
    op.create_index(op.f('ix_derived_metrics_metric_id'), 'derived_metrics', ['metric_id'], unique=False)
    op.create_index(op.f('ix_derived_metrics_observation_date'), 'derived_metrics', ['observation_date'], unique=False)
    op.create_table('series_catalog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fred_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('units', sa.String(length=64), nullable=False),
    sa.Column('frequency', sa.String(length=16), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('typical_lag_days', sa.Integer(), nullable=False),
    sa.Column('source_url', sa.String(length=512), nullable=True),
    sa.Column('last_ingest_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fred_id')
    )
    op.create_table('series_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fred_id', sa.String(length=32), nullable=False),
    sa.Column('observation_date', sa.Date(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('release_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingest_timestamp', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('is_revised', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fred_id', 'observation_date', name='uq_series_point')
    )
    op.create_index(op.f('ix_series_points_fred_id'), 'series_points', ['fred_id'], unique=False)
    op.create_index(op.f('ix_series_points_observation_date'), 'series_points', ['observation_date'], unique=False)
    op.create_table('summary_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('data_snapshot', sa.JSON(), nullable=False),
    sa.Column('template_version', sa.String(length=16), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_summary_runs_snapshot_date'), 'summary_runs', ['snapshot_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_summary_runs_snapshot_date'), table_name='summary_runs')
    op.drop_table('summary_runs')
    op.drop_index(op.f('ix_series_points_observation_date'), table_name='series_points')
    op.drop_index(op.f('ix_series_points_fred_id'), table_name='series_points')
    op.drop_table('series_points')
    op.drop_table('series_catalog')
    op.drop_index(op.f('ix_derived_metrics_observation_date'), table_name='derived_metrics')
    op.drop_index(op.f('ix_derived_metrics_metric_id'), table_name='derived_metrics')
    op.drop_table('derived_metrics')
    op.drop_index(op.f('ix_comparison_snapshots_observation_date'), table_name='comparison_snapshots')
    op.drop_table('comparison_snapshots')
    # ### end Alembic commands ###
